/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ElComponent {
    }
}
declare global {
    interface HTMLElComponentElement extends Components.ElComponent, HTMLStencilElement {
    }
    var HTMLElComponentElement: {
        prototype: HTMLElComponentElement;
        new (): HTMLElComponentElement;
    };
    interface HTMLElementTagNameMap {
        "el-component": HTMLElComponentElement;
    }
}
declare namespace LocalJSX {
    interface ElComponent {
    }
    interface IntrinsicElements {
        "el-component": ElComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "el-component": LocalJSX.ElComponent & JSXBase.HTMLAttributes<HTMLElComponentElement>;
        }
    }
}
