/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ElForm {
    }
    interface ElSpinner {
    }
}
declare global {
    interface HTMLElFormElement extends Components.ElForm, HTMLStencilElement {
    }
    var HTMLElFormElement: {
        prototype: HTMLElFormElement;
        new (): HTMLElFormElement;
    };
    interface HTMLElSpinnerElement extends Components.ElSpinner, HTMLStencilElement {
    }
    var HTMLElSpinnerElement: {
        prototype: HTMLElSpinnerElement;
        new (): HTMLElSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "el-form": HTMLElFormElement;
        "el-spinner": HTMLElSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface ElForm {
    }
    interface ElSpinner {
    }
    interface IntrinsicElements {
        "el-form": ElForm;
        "el-spinner": ElSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "el-form": LocalJSX.ElForm & JSXBase.HTMLAttributes<HTMLElFormElement>;
            "el-spinner": LocalJSX.ElSpinner & JSXBase.HTMLAttributes<HTMLElSpinnerElement>;
        }
    }
}
