

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-scope:

    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.file_changes.outputs.files }}

    steps:

    - id: checkout_current_repo
      uses: actions/checkout@master

    - id: file_changes
      uses: trilom/file-changes-action@master

  publish:
    runs-on: ubuntu-latest
    needs: detect-scope
    steps:

    - id: checkout_current_repo
      uses: actions/checkout@master

    - name: Publish all changed scope directories to NPM
      run: echo '${{ needs.detect-scope.outputs.files[0] }}'

