

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: 'package.json'


jobs:

  detect-scope:
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Check for package.json change
      run: echo "CHECK"


  publish:
    needs: detect-scope
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Publish all changed scope directories to NPM
      run: echo "PUBLISH"
