

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-scope:
    runs-on: ubuntu-latest
    steps:

    - id: checkout_current_repo
      uses: actions/checkout@master

    - id: file_changes
      uses: trilom/file-changes-action@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - id: test_output_check
      name: test
      run: echo '${{ steps.file_changes.outputs }}' | python -m json.tool


  publish:
    runs-on: ubuntu-latest
    needs: detect-scope
    steps:

    - id: checkout_current_repo
      uses: actions/checkout@master

    - name: Publish all changed scope directories to NPM
      run: echo ${{needs.detect-scope.file_changes.outputs}}

