

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-change:

    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.file_changes.outputs.files }}

    steps:

    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - id: file_changes
      name: https://github.com/marketplace/actions/file-changes-action
      uses: trilom/file-changes-action@v1.2.3

  detect-scope:

    runs-on: ubuntu-latest

    needs: detect-change

    outputs:
      scope: ${{ steps.get_scope.outputs.first_match }}

    steps:

    - name: test kr rha bia
      run: echo `${{ needs.detect-scope.outputs.files }}`

    # - id: get_scope
    #   name: Get scope as output using regex
    #   uses: AsasInnab/regex-action@v1
    #   with:
    #     regex_pattern: '(\w+)\/package.json'
    #     regex_flags: 'gim'
    #     search_string: '${{ needs.detect-scope.outputs.files }}'

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: detect-scope
  #   steps:

  #   - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     uses: actions/checkout@v2
  #     with:
  #       path: '/${{ needs.detect-scope.outputs.scope }}'

  #   - name: Set up Node.js
  #     uses: actions/setup-node@master
  #     with:
  #       node-version: 14.0.0

  #   - name: Publish to NLP if version has been updated
  #     uses: pascalgn/npm-publish-action@4f4bf159e299f65d21cd1cbd96fc5d53228036df
  #     with:
  #       commit_pattern: "^Release (\S+)"
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

