

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-change:

    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.file_changes.outputs.files }}

    steps:

    - id: checkout_current_repo
      uses: actions/checkout@v2

    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3

  publish:
    runs-on: ubuntu-latest
    needs: detect-change
    steps:

    - id: checkout_current_repo
      uses: actions/checkout@v2

    - name: Publish all changed scope directories to NPM
      run: echo '${{ needs.detect-change.outputs.files }}'

