

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-change:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.file_changes.outputs.files }}

    steps:

    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - id: file_changes
      name: https://github.com/marketplace/actions/file-changes-action
      uses: trilom/file-changes-action@v1.2.3

  detect-scope:
    runs-on: ubuntu-latest
    needs: detect-change

    outputs:
      scope: ${{ needs.detect-change.outputs.files }}

    steps:

    - name: detect the scope directory
      run: echo '${{ needs.detect-change.outputs.files }}'

  publish:
    runs-on: ubuntu-latest
    needs: detect-scope
    steps:
    - name: detect the scope directory
      run: echo '${{ needs.detect-scope.outputs.scope }}'

