

name: Publish to NPM Registry

on:

  # Trigger on push event
  push:

    # Only monitor master branch
    branches: master

    # Only detect changes in package.json file
    paths: '*/package.json'


jobs:

  detect-change:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.file_changes.outputs.files }}

    steps:

    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - id: file_changes
      name: https://github.com/marketplace/actions/file-changes-action
      uses: trilom/file-changes-action@v1.2.3

  detect-scope:
    runs-on: ubuntu-latest
    needs: detect-change

    outputs:
      scope: ${{ steps.trim_scope.outputs.scope }}

    steps:

    - id: get_scope
      name: Get scope as output using regex
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(\w+)\/package.json'
        regex_flags: 'gim'
        search_string: '${{ needs.detect-change.outputs.files }}'

    - id: trim_scope
      name: Get the scope value from regex selection
      run: |
        scope_dir="$(cut -d'/' -f1 <<<"${{ steps.get_scope.outputs.first_match }}")"
        echo "::set-output name=scope::$scope_dir"

  publish:
    runs-on: ubuntu-latest
    needs: detect-scope
    steps:

    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2

    - name: publish
      run: echo '${{ needs.detect-scope.outputs.scope }}'

